version: '3.8'

services:
  bitcoin-sanction-detector-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    container_name: sanction-detector-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
      - DATA_DIR=/app/data
      - ALLOWED_ORIGINS=*
    volumes:
      # Bind mount source code for hot reload
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      # Node modules cache
      - node_modules:/app/node_modules
    networks:
      - sanction-detector-dev-network
    command: npm run dev

networks:
  sanction-detector-dev-network:
    driver: bridge
    name: sanction-detector-dev-net

volumes:
  node_modules:
